# Welcome to Serverless!
#
service: profuct-service

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  profile: sdmAccount

  environment:
    PG_USER: postgres
    PG_DATABASE: lesson4
    PG_INSTANCE: node-aws-course-instance.chsb9nfhbw7v.eu-west-1.rds.amazonaws.com
    PG_PORT: 5432

plugins:
  - serverless-plugin-webpack

functions:
  getProductsList:
    handler: handler.getProductsList
    events:
      - http:
          path: products
          method: get
          cors: true
  getProductById:
    handler: handler.getProductById
    events:
      - http:
          path: product
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                id: true
