service: authorization-service

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  profile: sdmAccount

  environment:
    USER: ${env.USER}
    PASS: ${env.PASS}

plugins:
  - serverless-plugin-webpack
  - serverless-dotenv-plugin

functions:
  basicAuthorizer:
    handler: handler.basicAuthorizer

resources:
  Resources: {}
  Outputs:
    basicAuthorizerArn:
      Value:
        'Fn::GetAtt':
          - BasicAuthorizerLambdaFunction
          - Arn
