# Welcome to Serverless!
#
service: import-service

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  profile: sdmAccount

  environment:
    BUCKET_NAME: import-service
    PARSED_FOLDER: parsed/
    REGION: eu-west-1
    UPLOADED_FOLDER: uploaded/

  iamRoleStatements:
    - Action:
        - s3:ListBucket
      Effect: Allow
      Resource:
        - arn:aws:s3:::${self:provider.environment.BUCKET_NAME}
    - Action:
        - s3:*
      Effect: Allow
      Resource:
        - arn:aws:s3:::${self:provider.environment.BUCKET_NAME}/*

plugins:
  - serverless-plugin-webpack

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: ${self:provider.environment.BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - prefix: ${self:provider.environment.UPLOADED_FOLDER}
          existing: true
